spring:
  application:
    name: SmisUserDataAccess
  datasource:
    url: ${JDBC_POSTGRES_URL:jdbc:postgresql://localhost:1357/smis}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:Q4F8bM0G88pQ}
    password: ${POSTGRES_PASSWORD:ao7KlY3I\^5]29JeflR<}
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect