services:
  smis_postgres:
    image: postgres:13.16
    container_name: smis_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "1357:5432"
    shm_size: 128mb
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    networks:
      - ${GLOBAL_NETWORK:-smis_services}